### ISSUE TITLE
PostsList use 'fr' when no language used

### ISSUE THREAD

**Issue by MaciejTrojniarz** [maxpou/gatsby-starter-morning-dew#126] opened 2020-05-31 21:22 UTC

**Comment by MaciejTrojniarz** [comment] 2020-05-31 21:23
Potential solution is to use SiteMatedata:
```jsx
import React, { Fragment } from 'react'

import PostsListItem from './PostsListItem'
import useSiteMetadata from '../hooks/use-site-config'

class PostsList extends React.Component {
  render() {
    const { posts } = this.props
    const { defaultLang } = useSiteMetadata()
    return (
      <Fragment>
        {posts.map(post => {
          const props = {
            title: post.node.frontmatter.title,
            excerpt: post.node.excerpt,
            slug: post.node.frontmatter.slug,
            timeToRead: post.node.timeToRead,
            language: post.node.frontmatter.language || defaultLang,
            tags: post.node.frontmatter.tags || [],
          }
          return <PostsListItem key={props.slug} {...props} />
        })}
      </Fragment>
    )
  }
}
export default PostsList
```

**Comment by maxpou** [comment] 2020-06-01 10:44
Thanks for the feedback @MaciejTrojniarz. #127 should fix this :)
(about your suggestion: it almost worked!! but we can't use hooks in class based component!)

**Comment by maxpou** [comment] 2020-06-01 17:21
Should be fixed now. Give me a shout if the problem is still there :)

**Closed as completed by maxpou** 2020-06-01 17:21 UTC
